INSERT INTO public.topic(
	topic_id, topic_label)
	VALUES
	(101, 'Programming'),
	(102, 'Data Structures'),
    (103, 'Algorithms'),
    (104, 'Web Development'),
    (105, 'Database Management'),
    (106, 'Mobile App Development'),
    (107, 'Machine Learning'),
    (108, 'Computer Networks'),
    (109, 'Operating Systems'),
    (110, 'Software Engineering'),
    (111, 'Artificial Intelligence'),
    (112, 'Cybersecurity'),
    (113, 'Cloud Computing'),
    (114, 'Game Development'),
    (115, 'Blockchain'),
    (116, 'DevOps'),
    (117, 'UI/UX Design'),
    (118, 'Big Data'),
    (119, 'Embedded Systems'),
    (120, 'Robotics'),
    (121, 'IoT'),
    (122, 'Data Analysis'),
    (123, 'Computer Graphics'),
    (124, 'Bioinformatics'),
    (125, 'Quantum Computing'),
    (126, 'Natural Language Processing'),
    (127, 'Virtual Reality'),
    (128, 'Augmented Reality'),
    (129, 'Information Retrieval'),
    (130, 'Cryptography'),
    (131, 'Parallel Computing'),
    (132, 'Wireless Communication'),
    (133, 'Compiler Design'),
    (134, 'Distributed Systems'),
    (135, 'Image Processing'),
    (136, 'Human-Computer Interaction'),
    (137, 'Cyber-Physical Systems'),
    (138, 'Computer Vision'),
    (139, 'Internet Security'),
    (140, 'Semantic Web'),
    (141, 'Neural Networks'),
    (142, 'Computer Architecture'),
    (143, 'FPGA Design'),
    (144, 'Network Security'),
    (145, 'Bioinformatics'),
    (146, 'Cloud Security'),
    (147, 'Software Testing'),
    (148, 'Embedded Software'),
    (149, 'Database Security'),
    (150, 'Web Security'),
    (151, 'Data Mining'),
    (152, 'Privacy Protection'),
    (153, 'Wireless Sensor Networks'),
    (154, 'Deep Learning'),
    (155, 'Quantum Cryptography'),
    (156, 'AR/VR Development'),
    (157, 'Edge Computing'),
    (158, 'Biometric Security'),
    (159, 'Graph Theory'),
    (160, 'Geographic Information Systems');


INSERT INTO task(created_at, task_id, topic_id, status, task_description, task_label)
VALUES
    	(NOW() - INTERVAL '1 day', 1, 101, 'TODO', 'Implement user authentication', 'User Authentication'),
        (NOW() - INTERVAL '2 day', 2, 102, 'IN_PROGRESS', 'Design homepage layout', 'Homepage Design'),
        (NOW() - INTERVAL '3 day', 3, 103, 'DONE', 'Fix login page bugs', 'Login Page Fixes'),
        (NOW() - INTERVAL '4 day', 4, 104, 'TODO', 'Create user profile page', 'User Profile Page Creation'),
        (NOW() - INTERVAL '5 day', 5, 105, 'TODO', 'Implement search functionality', 'Search Functionality Implementation'),
        (NOW() - INTERVAL '6 day', 6, 106, 'IN_PROGRESS', 'Optimize database queries', 'Database Query Optimization'),
        (NOW() - INTERVAL '7 day', 7, 107, 'TODO', 'Write API documentation', 'API Documentation Writing'),
        (NOW() - INTERVAL '8 day', 8, 108, 'DONE', 'Test new features', 'Feature Testing'),
        (NOW() - INTERVAL '9 day', 9, 109, 'TODO', 'Fix CSS issues', 'CSS Bug Fixes'),
        (NOW() - INTERVAL '10 day', 10, 110, 'TODO', 'Implement user preferences', 'User Preferences Implementation'),
        (NOW() - INTERVAL '11 day', 11, 111, 'IN_PROGRESS', 'Create admin dashboard', 'Admin Dashboard Creation'),
        (NOW() - INTERVAL '12 day', 12, 112, 'TODO', 'Refactor codebase', 'Codebase Refactoring'),
        (NOW() - INTERVAL '13 day', 13, 113, 'DONE', 'Review pull requests', 'Pull Request Reviews'),
        (NOW() - INTERVAL '14 day', 14, 114, 'TODO', 'Implement file upload functionality', 'File Upload Implementation'),
        (NOW() - INTERVAL '15 day', 15, 115, 'TODO', 'Update documentation', 'Documentation Updates'),
        (NOW() - INTERVAL '16 day', 16, 116, 'IN_PROGRESS', 'Create landing page', 'Landing Page Creation'),
        (NOW() - INTERVAL '17 day', 17, 117, 'TODO', 'Optimize frontend performance', 'Frontend Performance Optimization'),
        (NOW() - INTERVAL '18 day', 18, 118, 'DONE', 'Refine user interface', 'UI Refinement'),
        (NOW() - INTERVAL '19 day', 19, 119, 'TODO', 'Integrate payment gateway', 'Payment Gateway Integration'),
        (NOW() - INTERVAL '20 day', 20, 120, 'TODO', 'Implement email notifications', 'Email Notifications Implementation'),
        (NOW() - INTERVAL '21 day', 21, 121, 'IN_PROGRESS', 'Add user feedback feature', 'User Feedback Feature Addition'),
        (NOW() - INTERVAL '22 day', 22, 122, 'TODO', 'Fix database indexing issues', 'Database Indexing Fixes'),
        (NOW() - INTERVAL '23 day', 23, 123, 'DONE', 'Update terms of service', 'Terms of Service Update'),
        (NOW() - INTERVAL '24 day', 24, 124, 'TODO', 'Implement role-based access control', 'RBAC Implementation'),
        (NOW() - INTERVAL '25 day', 25, 125, 'TODO', 'Create user onboarding flow', 'User Onboarding Flow Creation'),
        (NOW() - INTERVAL '26 day', 26, 126, 'IN_PROGRESS', 'Optimize server performance', 'Server Performance Optimization'),
        (NOW() - INTERVAL '27 day', 27, 127, 'TODO', 'Implement push notifications', 'Push Notifications Implementation'),
        (NOW() - INTERVAL '28 day', 28, 128, 'DONE', 'Review user feedback', 'User Feedback Reviews'),
        (NOW() - INTERVAL '29 day', 29, 129, 'TODO', 'Update privacy policy', 'Privacy Policy Update'),
        (NOW() - INTERVAL '30 day', 30, 130, 'TODO', 'Integrate social media login', 'Social Media Login Integration'),
        (NOW() - INTERVAL '31 day', 31, 131, 'IN_PROGRESS', 'Create user surveys', 'User Surveys Creation'),
        (NOW() - INTERVAL '32 day', 32, 132, 'TODO', 'Fix broken links', 'Broken Links Fixes'),
        (NOW() - INTERVAL '33 day', 33, 133, 'DONE', 'Optimize SEO', 'SEO Optimization'),
        (NOW() - INTERVAL '34 day', 34, 134, 'TODO', 'Implement analytics tracking', 'Analytics Tracking Implementation'),
        (NOW() - INTERVAL '35 day', 35, 135, 'TODO', 'Create user forums', 'User Forums Creation'),
    	(NOW() - INTERVAL '36 day', 36, 136, 'TODO', 'Implement chat functionality', 'Chat Functionality Implementation'),
        (NOW() - INTERVAL '37 day', 37, 137, 'IN_PROGRESS', 'Create user dashboard', 'User Dashboard Creation'),
        (NOW() - INTERVAL '38 day', 38, 138, 'DONE', 'Review codebase', 'Codebase Review'),
        (NOW() - INTERVAL '39 day', 39, 139, 'TODO', 'Fix performance bottlenecks', 'Performance Fixes'),
        (NOW() - INTERVAL '40 day', 40, 140, 'TODO', 'Implement subscription feature', 'Subscription Feature Implementation'),
        (NOW() - INTERVAL '41 day', 41, 141, 'IN_PROGRESS', 'Design email templates', 'Email Template Design'),
        (NOW() - INTERVAL '42 day', 42, 142, 'TODO', 'Optimize database schema', 'Database Schema Optimization'),
        (NOW() - INTERVAL '43 day', 43, 143, 'DONE', 'Update application documentation', 'Documentation Update'),
        (NOW() - INTERVAL '44 day', 44, 144, 'TODO', 'Add CAPTCHA to registration', 'CAPTCHA Integration'),
        (NOW() - INTERVAL '45 day', 45, 145, 'TODO', 'Implement file storage solution', 'File Storage Implementation'),
        (NOW() - INTERVAL '46 day', 46, 146, 'IN_PROGRESS', 'Refactor frontend code', 'Frontend Refactoring'),
        (NOW() - INTERVAL '47 day', 47, 147, 'TODO', 'Update privacy settings', 'Privacy Settings Update'),
        (NOW() - INTERVAL '48 day', 48, 148, 'DONE', 'Perform security audit', 'Security Audit'),
        (NOW() - INTERVAL '49 day', 49, 149, 'TODO', 'Implement user notifications', 'User Notifications Implementation'),
        (NOW() - INTERVAL '50 day', 50, 150, 'TODO', 'Update terms and conditions', 'Terms and Conditions Update'),
        (NOW() - INTERVAL '51 day', 51, 151, 'IN_PROGRESS', 'Create user roles', 'User Roles Creation'),
        (NOW() - INTERVAL '52 day', 52, 152, 'TODO', 'Optimize image loading', 'Image Loading Optimization'),
        (NOW() - INTERVAL '53 day', 53, 153, 'DONE', 'Test application on different browsers', 'Cross-browser Testing'),
        (NOW() - INTERVAL '54 day', 54, 154, 'TODO', 'Implement password strength meter', 'Password Strength Meter Implementation'),
        (NOW() - INTERVAL '55 day', 55, 155, 'TODO', 'Create user tutorials', 'User Tutorials Creation'),
        (NOW() - INTERVAL '56 day', 56, 156, 'IN_PROGRESS', 'Design landing page', 'Landing Page Design'),
        (NOW() - INTERVAL '57 day', 57, 157, 'TODO', 'Optimize mobile responsiveness', 'Mobile Responsiveness Optimization'),
        (NOW() - INTERVAL '58 day', 58, 158, 'DONE', 'Create backup system', 'Backup System Creation'),
        (NOW() - INTERVAL '59 day', 59, 159, 'TODO', 'Implement user surveys', 'User Surveys Implementation'),
        (NOW() - INTERVAL '60 day', 60, 160, 'TODO', 'Update error handling', 'Error Handling Update');